name: Run Python script on push

on:
  push:
    branches:
      - main  # 푸시 이벤트를 원하는 브랜치로 변경하세요

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run Python script
      run: python .github/action.py ${{ github.event_name }} "${{ github.event.head_commit.message }}"

