name: send commit msg on push

on:
  push:
    branches:
      - main  # 푸시 이벤트를 원하는 브랜치로 변경하세요

jobs:
  run_action_python:
    runs-on: ubuntu-latest
    name: Run Python script

    steps:
	- uses: actions/checkout@v2
    - run: python .github/action.py "${{ github.event.head_commit.message }}"
	- run: echo "HEllo world"
#    - run: python .github/action.py ${{ github.event_name }} "${{ github.event.head_commit.message }}"

